name: C++ Cross-Platform Build

on: push

defaults:
  run:
    shell: bash

jobs:

  clang-format-check:
    name: clang-format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '14'

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
        mode: [ "Debug", "Release" ]
        include:
          - os: ubuntu-22.04
            #cxx-override: CC=gcc-10 CXX=g++-10
          - os: macos-12
          - os: windows-2022
            pdb-path: ./build/*.pdb

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: apt dependencies
        run: sudo apt update && sudo apt install -y --no-install-recommends libtbb-dev
        if: startsWith(matrix.os, 'ubuntu')

      - name: Configure
        run: |
          mkdir build
          cd build
          ${{ matrix.cxx-override }} \
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.mode }} ..

      - name: Build
        working-directory: build
        run: cmake --build . --config ${{ matrix.mode }}
